import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/app/components/navbar/NavbarComponent";
import PageTransitionWrapper from "@/app/components/transition/PageTransitionWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Empresa moderna - Página ejemplos",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased m-4`}
        >

        <NavbarComponent/>

        <main className={`font-sans m-4`}>
            <PageTransitionWrapper>
                {children}
            </PageTransitionWrapper>
        </main>


        </body>
        </html>
    );
}
